name: immigru
description: A Flutter application for immigration services with clean architecture.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: 9.1.1
  provider: ^6.0.3
  equatable: ^2.0.5
  app_links: ^6.4.0

  # Dependency injection
  get_it: ^8.0.3

  # Network
  dio: ^5.3.2
  http: ^1.0.0
  pretty_dio_logger: ^1.3.1
  geocoding: ^2.1.0

  # Supabase
  supabase_flutter: ^2.9.0

  # Authentication
  google_sign_in: ^6.3.0

  # Storage
  shared_preferences: ^2.2.0

  # UI
  flutter_svg: ^2.0.7
  google_fonts: ^6.2.1
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  intl_phone_field: ^3.2.0

  # Form validation
  formz: ^0.8.0

  # Utils
  intl: ^0.20.2
  url_launcher: ^6.1.12
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  path: ^1.8.3
  uuid: ^4.2.1

  # Apple Sign-In (updated versions)
  sign_in_with_apple: ^7.0.1
  sign_in_with_apple_platform_interface: ^2.0.0
  sign_in_with_apple_web: ^3.0.0
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  mockito: ^5.4.2
  bloc_test: ^10.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/immigru-logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
